export const MOCK_PLAYERS = [
  {
    id: "PF21",
    name: "Peter Forsberg",
    jerseyNumber: "21",
    position: "Center",
    team: "Colorado Avalanche",
    goals: "15",
    assists: "35",
    gamesPlayed: "20",
  },
  {
    id: "MS13",
    name: "Mats Sundin",
    jerseyNumber: "13",
    position: "Center",
    team: "Toronto Maple Leafs",
    goals: "20",
    assists: "40",
    gamesPlayed: "25",
  },
  {
    id: "WJ99",
    name: "Wayne Gretzky",
    jerseyNumber: "99",
    position: "Center",
    team: "Edmonton Oilers",
    goals: "25",
    assists: "60",
    gamesPlayed: "30",
  },
  {
    id: "SG8",
    name: "Sidney Crosby",
    jerseyNumber: "87",
    position: "Center",
    team: "Pittsburgh Penguins",
    goals: "30",
    assists: "50",
    gamesPlayed: "30",
  },
  {
    id: "AO8",
    name: "Alex Ovechkin",
    jerseyNumber: "8",
    position: "Left Wing",
    team: "Washington Capitals",
    goals: "40",
    assists: "30",
    gamesPlayed: "30",
  },
  {
    id: "PK76",
    name: "P.K. Subban",
    jerseyNumber: "76",
    position: "Defense",
    team: "Nashville Predators",
    goals: "10",
    assists: "25",
    gamesPlayed: "30",
  },
  {
    id: "EH9",
    name: "Eric Lindros",
    jerseyNumber: "88",
    position: "Center",
    team: "Philadelphia Flyers",
    goals: "25",
    assists: "35",
    gamesPlayed: "28",
  },
  {
    id: "JS26",
    name: "Joe Sakic",
    jerseyNumber: "19",
    position: "Center",
    team: "Colorado Avalanche",
    goals: "20",
    assists: "45",
    gamesPlayed: "29",
  },
  {
    id: "CM16",
    name: "Connor McDavid",
    jerseyNumber: "97",
    position: "Center",
    team: "Edmonton Oilers",
    goals: "35",
    assists: "60",
    gamesPlayed: "32",
  },
  {
    id: "AN11",
    name: "Anze Kopitar",
    jerseyNumber: "11",
    position: "Center",
    team: "Los Angeles Kings",
    goals: "18",
    assists: "40",
    gamesPlayed: "27",
  },
  {
    id: "DP4",
    name: "Dion Phaneuf",
    jerseyNumber: "3",
    position: "Defense",
    team: "Toronto Maple Leafs",
    goals: "5",
    assists: "20",
    gamesPlayed: "26",
  },
  {
    id: "RA33",
    name: "Ray Bourque",
    jerseyNumber: "77",
    position: "Defense",
    team: "Boston Bruins",
    goals: "8",
    assists: "30",
    gamesPlayed: "30",
  },
  {
    id: "IB22",
    name: "Igor Larionov",
    jerseyNumber: "22",
    position: "Center",
    team: "Detroit Red Wings",
    goals: "12",
    assists: "35",
    gamesPlayed: "29",
  },
  {
    id: "NZ44",
    name: "Zdeno Chara",
    jerseyNumber: "33",
    position: "Defense",
    team: "Boston Bruins",
    goals: "7",
    assists: "18",
    gamesPlayed: "28",
  },
  {
    id: "HS28",
    name: "Henrik Sedin",
    jerseyNumber: "33",
    position: "Center",
    team: "Vancouver Canucks",
    goals: "15",
    assists: "40",
    gamesPlayed: "30",
  },
  {
    id: "JS12",
    name: "Joe Thornton",
    jerseyNumber: "19",
    position: "Center",
    team: "San Jose Sharks",
    goals: "10",
    assists: "50",
    gamesPlayed: "28",
  },
  {
    id: "RS92",
    name: "Ryan Smyth",
    jerseyNumber: "94",
    position: "Left Wing",
    team: "Edmonton Oilers",
    goals: "22",
    assists: "30",
    gamesPlayed: "30",
  },
  {
    id: "HS6",
    name: "Hayley Wickenheiser",
    jerseyNumber: "22",
    position: "Center",
    team: "Calgary Flames",
    goals: "18",
    assists: "25",
    gamesPlayed: "28",
  },
  {
    id: "LP20",
    name: "Lanny McDonald",
    jerseyNumber: "9",
    position: "Right Wing",
    team: "Calgary Flames",
    goals: "25",
    assists: "20",
    gamesPlayed: "30",
  },
  {
    id: "ML27",
    name: "Mikko Rantanen",
    jerseyNumber: "96",
    position: "Right Wing",
    team: "Colorado Avalanche",
    goals: "35",
    assists: "40",
    gamesPlayed: "30",
  },
  {
    id: "GG33",
    name: "Gordie Howe",
    jerseyNumber: "9",
    position: "Right Wing",
    team: "Detroit Red Wings",
    goals: "30",
    assists: "40",
    gamesPlayed: "30",
  },
  {
    id: "BL41",
    name: "Brian Leetch",
    jerseyNumber: "2",
    position: "Defense",
    team: "New York Rangers",
    goals: "10",
    assists: "45",
    gamesPlayed: "30",
  },
  {
    id: "MP66",
    name: "Mario Lemieux",
    jerseyNumber: "66",
    position: "Center",
    team: "Pittsburgh Penguins",
    goals: "50",
    assists: "60",
    gamesPlayed: "30",
  },
  {
    id: "JG72",
    name: "Jaromir Jagr",
    jerseyNumber: "68",
    position: "Right Wing",
    team: "Pittsburgh Penguins",
    goals: "40",
    assists: "50",
    gamesPlayed: "30",
  },
  {
    id: "TG71",
    name: "Taylor Hall",
    jerseyNumber: "9",
    position: "Left Wing",
    team: "New Jersey Devils",
    goals: "22",
    assists: "35",
    gamesPlayed: "30",
  },
  {
    id: "ZM13",
    name: "Zach Parise",
    jerseyNumber: "11",
    position: "Left Wing",
    team: "Minnesota Wild",
    goals: "28",
    assists: "25",
    gamesPlayed: "30",
  },
  {
    id: "TH29",
    name: "Teemu Selanne",
    jerseyNumber: "8",
    position: "Right Wing",
    team: "Anaheim Ducks",
    goals: "45",
    assists: "40",
    gamesPlayed: "30",
  },
  {
    id: "KS23",
    name: "Keith Tkachuk",
    jerseyNumber: "7",
    position: "Left Wing",
    team: "St. Louis Blues",
    goals: "30",
    assists: "25",
    gamesPlayed: "30",
  },
  {
    id: "PK9",
    name: "Paul Kariya",
    jerseyNumber: "9",
    position: "Left Wing",
    team: "Anaheim Ducks",
    goals: "35",
    assists: "30",
    gamesPlayed: "30",
  },
  {
    id: "DB10",
    name: "Dustin Brown",
    jerseyNumber: "23",
    position: "Right Wing",
    team: "Los Angeles Kings",
    goals: "18",
    assists: "22",
    gamesPlayed: "30",
  },
];

export const MOCK_TEAMS = [
  {
    name: "Toronto Maple Leafs",
    points: 25,
    wins: 9,
    draws: 2,
    losses: 10,
    players: [
      { id: "MS13", name: "Mats Sundin" },
      { id: "DP4", name: "Dion Phaneuf" },
    ],
  },
  {
    name: "Colorado Avalanche",
    points: 21,
    wins: 8,
    draws: 3,
    losses: 12,
    players: [
      { id: "PF21", name: "Peter Forsberg" },
      { id: "JS26", name: "Joe Sakic" },
      { id: "ML27", name: "Mikko Rantanen" },
    ],
  },
  {
    name: "Edmonton Oilers",
    points: 15,
    wins: 5,
    draws: 0,
    losses: 17,
    players: [
      { id: "WJ99", name: "Wayne Gretzky" },
      { id: "CM16", name: "Connor McDavid" },
      { id: "RS92", name: "Ryan Smyth" },
    ],
  },
  {
    name: "Pittsburgh Penguins",
    points: 3,
    wins: 1,
    draws: 0,
    losses: 25,
    players: [
      { id: "SG8", name: "Sidney Crosby" },
      { id: "MP66", name: "Mario Lemieux" },
      { id: "JG72", name: "Jaromir Jagr" },
    ],
  },
  {
    name: "Washington Capitals",
    points: 25,
    wins: 9,
    draws: 2,
    losses: 10,
    players: [{ id: "AO8", name: "Alex Ovechkin" }],
  },
  {
    name: "Nashville Predators",
    points: 3,
    wins: 1,
    draws: 0,
    losses: 25,
    players: [{ id: "PK76", name: "P.K. Subban" }],
  },
  {
    name: "Philadelphia Flyers",
    points: 3,
    wins: 1,
    draws: 0,
    losses: 25,
    players: [{ id: "EH9", name: "Eric Lindros" }],
  },
  {
    name: "Los Angeles Kings",
    points: 15,
    wins: 5,
    draws: 0,
    losses: 17,
    players: [
      { id: "AN11", name: "Anze Kopitar" },
      { id: "DB10", name: "Dustin Brown" },
    ],
  },
  {
    name: "Boston Bruins",
    points: 19,
    wins: 8,
    draws: 5,
    losses: 0,
    players: [
      { id: "RA33", name: "Ray Bourque" },
      { id: "NZ44", name: "Zdeno Chara" },
    ],
  },
  {
    name: "Detroit Red Wings",
    points: 19,
    wins: 8,
    draws: 5,
    losses: 0,
    players: [
      { id: "IB22", name: "Igor Larionov" },
      { id: "GG33", name: "Gordie Howe" },
    ],
  },
  {
    name: "Vancouver Canucks",
    points: 19,
    wins: 8,
    draws: 5,
    losses: 0,
    players: [{ id: "HS28", name: "Henrik Sedin" }],
  },
  {
    name: "San Jose Sharks",
    points: 10,
    wins: 3,
    draws: 1,
    losses: 20,
    players: [{ id: "JS12", name: "Joe Thornton" }],
  },
  {
    name: "Calgary Flames",
    points: 10,
    wins: 3,
    draws: 1,
    losses: 20,
    players: [
      { id: "HS6", name: "Hayley Wickenheiser" },
      { id: "LP20", name: "Lanny McDonald" },
    ],
  },
  {
    name: "New Jersey Devils",
    points: 10,
    wins: 3,
    draws: 1,
    losses: 20,
    players: [{ id: "TG71", name: "Taylor Hall" }],
  },
  {
    name: "Minnesota Wild",
    players: [{ id: "ZM13", name: "Zach Parise" }],
  },
  {
    name: "Anaheim Ducks",
    points: 10,
    wins: 3,
    draws: 1,
    losses: 20,
    players: [
      { id: "TH29", name: "Teemu Selanne" },
      { id: "PK9", name: "Paul Kariya" },
    ],
  },
  {
    name: "St. Louis Blues",
    points: 20,
    wins: 6,
    draws: 2,
    losses: 10,
    players: [{ id: "KS23", name: "Keith Tkachuk" }],
  },
  {
    name: "New York Rangers",
    points: 30,
    wins: 20,
    draws: 0,
    losses: 0,
    players: [{ id: "BL41", name: "Brian Leetch" }],
  },
];

export const MOCK_GAMES = [
  {
    homeTeam: "Minnesota Wild",
    awayTeam: "Toronto Maple Leafs",
    startTime: "JUNE 16, 2024 18:00 AM",
    homeTeamGoals: 3,
    awayTeamGoals: 1,
  },
  {
    homeTeam: "Detroit Red Wings",
    awayTeam: "Toronto Maple Leafs",
    startTime: "JUNE 20, 2024 12:00 AM",
    homeTeamGoals: 0,
    awayTeamGoals: 0,
  },
  {
    homeTeam: "New York Rangers",
    awayTeam: "Boston Bruins",
    startTime: "JUNE 22, 2024 15:30 PM",
    homeTeamGoals: 0,
    awayTeamGoals: 0,
  },
  {
    homeTeam: "Chicago Blackhawks",
    awayTeam: "Montreal Canadiens",
    startTime: "JUNE 23, 2024 19:45 PM",
    homeTeamGoals: 0,
    awayTeamGoals: 0,
  },
  {
    homeTeam: "Edmonton Oilers",
    awayTeam: "Vancouver Canucks",
    startTime: "JUNE 25, 2024 20:15 PM",
    homeTeamGoals: 0,
    awayTeamGoals: 0,
  },
  {
    homeTeam: "Calgary Flames",
    awayTeam: "Los Angeles Kings",
    startTime: "JUNE 06, 2024 17:00 PM",
    homeTeamGoals: 3,
    awayTeamGoals: 2,
  },
  {
    homeTeam: "Washington Capitals",
    awayTeam: "Philadelphia Flyers",
    startTime: "JUNE 08, 2024 18:30 PM",
    homeTeamGoals: 4,
    awayTeamGoals: 1,
  },
  {
    homeTeam: "San Jose Sharks",
    awayTeam: "Arizona Coyotes",
    startTime: "MAY 30, 2024 19:00 PM",
    homeTeamGoals: 2,
    awayTeamGoals: 0,
  },
];
